### ISSUE TITLE
能出一个java的么

### ISSUE THREAD

**Issue by fs185085781** [kazutoiris/ali_ecc#3]
研究了好久了,我的python和go版本都正常,就java死活没搞定,不知道算法哪里出了问题,换了十几个版本还是不行,有招嘛

**Comment by kazutoiris** [comment]
1. Check the ECC algorithm is `SECP256k1`.

    You can use the private key in the project, and compare the public key to see if they are same. If not, maybe the algorithm is wrong.

    (**Notice:** I'm not sure if it supports 02/03 compressed public key. More information:  https://asecuritysite.com/ecc/js_ethereum2)

2. Check whether this problem occurs on `create_session` or `renew_session`.

**Comment by aston314** [comment]
有javascript版本么？

**Comment by kazutoiris** [comment]
> 有javascript版本么？

You can use `secp256k1-node` or other packages for JavaScript.

There may be no official support recently.

**Comment by fs185085781** [comment]
> 1. 检查 ECC 算法是否为 。`SECP256k1`
>    您可以在项目中使用私钥，并比较公钥以查看它们是否相同。如果不是，也许算法是错误的。
>    (**通知：**我不确定它是否支持 02/03 压缩公钥。详细信息： https://asecuritysite.com/ecc/js_ethereum2)
> 2. 检查 或 上是否出现此问题。`create_session``renew_session`

搞定了
