### ISSUE TITLE
{"result":false,"success":true,"code":null,"message":null}

### ISSUE THREAD

**Issue by fntp** [kazutoiris/ali_ecc#5]
just one question,emmm
 
this param =》 ‘nonce’ 
I got this with random number called '0' or other value,but the request result always failed 
 the response is

{"result":false,"success":true,"code":null,"message":null}

I write this pr with Java-secp256k1

~

**Comment by fntp** [comment]
i don't know if u have any account in ['qq','wechat','telegram']
I'd like to talk about it with u and share my code

**Comment by kazutoiris** [comment]
`nonce` is **not** a random number. When `create session`, nonce is 0. When `refresh session`, nonce is nonce + 1.

There're some test cases in the `ali_ecc.py`, you can test the sign algorithm and so on.

**Comment by fntp** [comment]
I have modified this number-value, but..........

always response with {"result":false,"success":true,"code":null,"message":null} 

eh......

**Comment by fntp** [comment]
u could see this problem , here u are 
![image](https://user-images.githubusercontent.com/46984923/222679269-c5b6369b-55ae-469a-8e61-8263af5ccc6d.png)

I'd like to share my idea with u, but I patched the socket and found noting in bundle.js
